#!/bin/bash
#SBATCH --job-name=KNNSV
#SBATCH --mail-type=begin
#SBATCH --mail-type=end
#SBATCH --mail-type=fail
#SBATCH --mail-user=tw8948@princeton.edu
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=8G
#SBATCH --time=23:59:59

#SBATCH --constraint=skylake

#SBATCH --output=/scratch/gpfs/tw8948/slurm-%j.out
#SBATCH --error=/scratch/gpfs/tw8948/slurm-%j.out

python applications_knn.py --task mislabel_detect --dataset 2dplanes --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-2dplanes-Ntrain200-Nval200-K25-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset cpu --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-cpu-Ntrain200-Nval200-K25-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset phoneme --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-phoneme-Ntrain200-Nval200-K25-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset fraud --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-fraud-Ntrain200-Nval200-K25-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset creditcard --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-creditcard-Ntrain200-Nval200-K25-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset vehicle --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-vehicle-Ntrain200-Nval200-K25-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset click --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-click-Ntrain200-Nval200-K25-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset wind --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-wind-Ntrain200-Nval200-K25-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset pol --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-pol-Ntrain200-Nval200-K25-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset 2dplanes --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-2dplanes-Ntrain200-Nval200-K50-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset cpu --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-cpu-Ntrain200-Nval200-K50-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset phoneme --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-phoneme-Ntrain200-Nval200-K50-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset fraud --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-fraud-Ntrain200-Nval200-K50-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset creditcard --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-creditcard-Ntrain200-Nval200-K50-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset vehicle --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-vehicle-Ntrain200-Nval200-K50-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset click --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-click-Ntrain200-Nval200-K50-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset wind --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-wind-Ntrain200-Nval200-K50-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset pol --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-pol-Ntrain200-Nval200-K50-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset 2dplanes --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-2dplanes-Ntrain200-Nval200-K25-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset cpu --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-cpu-Ntrain200-Nval200-K25-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset phoneme --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-phoneme-Ntrain200-Nval200-K25-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset fraud --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-fraud-Ntrain200-Nval200-K25-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset creditcard --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-creditcard-Ntrain200-Nval200-K25-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset vehicle --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-vehicle-Ntrain200-Nval200-K25-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset click --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-click-Ntrain200-Nval200-K25-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset wind --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-wind-Ntrain200-Nval200-K25-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset pol --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-pol-Ntrain200-Nval200-K25-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset 2dplanes --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-2dplanes-Ntrain200-Nval200-K50-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset cpu --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-cpu-Ntrain200-Nval200-K50-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset phoneme --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-phoneme-Ntrain200-Nval200-K50-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset fraud --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-fraud-Ntrain200-Nval200-K50-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset creditcard --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-creditcard-Ntrain200-Nval200-K50-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset vehicle --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-vehicle-Ntrain200-Nval200-K50-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset click --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-click-Ntrain200-Nval200-K50-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset wind --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-wind-Ntrain200-Nval200-K50-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset pol --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-pol-Ntrain200-Nval200-K50-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset 2dplanes --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-2dplanes-Ntrain200-Nval200-K25-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset cpu --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-cpu-Ntrain200-Nval200-K25-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset phoneme --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-phoneme-Ntrain200-Nval200-K25-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset fraud --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-fraud-Ntrain200-Nval200-K25-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset creditcard --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-creditcard-Ntrain200-Nval200-K25-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset vehicle --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-vehicle-Ntrain200-Nval200-K25-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset click --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-click-Ntrain200-Nval200-K25-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset wind --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-wind-Ntrain200-Nval200-K25-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset pol --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-pol-Ntrain200-Nval200-K25-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset 2dplanes --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-2dplanes-Ntrain200-Nval200-K50-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset cpu --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-cpu-Ntrain200-Nval200-K50-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset phoneme --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-phoneme-Ntrain200-Nval200-K50-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset fraud --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-fraud-Ntrain200-Nval200-K50-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset creditcard --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-creditcard-Ntrain200-Nval200-K50-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset vehicle --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-vehicle-Ntrain200-Nval200-K50-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset click --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-click-Ntrain200-Nval200-K50-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset wind --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-wind-Ntrain200-Nval200-K50-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset pol --value_type KNN-SV-RJ --n_data 200 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-pol-Ntrain200-Nval200-K50-Kernel-plain-dist-l2.txt


python applications_knn.py --task mislabel_detect --dataset 2dplanes --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-2dplanes-Ntrain500-Nval200-K25-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset cpu --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-cpu-Ntrain500-Nval200-K25-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset phoneme --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-phoneme-Ntrain500-Nval200-K25-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset fraud --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-fraud-Ntrain500-Nval200-K25-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset creditcard --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-creditcard-Ntrain500-Nval200-K25-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset vehicle --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-vehicle-Ntrain500-Nval200-K25-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset click --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-click-Ntrain500-Nval200-K25-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset wind --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-wind-Ntrain500-Nval200-K25-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset pol --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-pol-Ntrain500-Nval200-K25-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset 2dplanes --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-2dplanes-Ntrain500-Nval200-K50-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset cpu --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-cpu-Ntrain500-Nval200-K50-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset phoneme --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-phoneme-Ntrain500-Nval200-K50-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset fraud --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-fraud-Ntrain500-Nval200-K50-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset creditcard --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-creditcard-Ntrain500-Nval200-K50-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset vehicle --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-vehicle-Ntrain500-Nval200-K50-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset click --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-click-Ntrain500-Nval200-K50-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset wind --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-wind-Ntrain500-Nval200-K50-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset pol --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-pol-Ntrain500-Nval200-K50-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset 2dplanes --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-2dplanes-Ntrain500-Nval200-K25-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset cpu --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-cpu-Ntrain500-Nval200-K25-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset phoneme --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-phoneme-Ntrain500-Nval200-K25-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset fraud --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-fraud-Ntrain500-Nval200-K25-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset creditcard --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-creditcard-Ntrain500-Nval200-K25-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset vehicle --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-vehicle-Ntrain500-Nval200-K25-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset click --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-click-Ntrain500-Nval200-K25-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset wind --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-wind-Ntrain500-Nval200-K25-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset pol --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-pol-Ntrain500-Nval200-K25-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset 2dplanes --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-2dplanes-Ntrain500-Nval200-K50-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset cpu --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-cpu-Ntrain500-Nval200-K50-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset phoneme --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-phoneme-Ntrain500-Nval200-K50-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset fraud --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-fraud-Ntrain500-Nval200-K50-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset creditcard --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-creditcard-Ntrain500-Nval200-K50-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset vehicle --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-vehicle-Ntrain500-Nval200-K50-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset click --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-click-Ntrain500-Nval200-K50-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset wind --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-wind-Ntrain500-Nval200-K50-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset pol --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-pol-Ntrain500-Nval200-K50-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset 2dplanes --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-2dplanes-Ntrain500-Nval200-K25-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset cpu --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-cpu-Ntrain500-Nval200-K25-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset phoneme --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-phoneme-Ntrain500-Nval200-K25-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset fraud --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-fraud-Ntrain500-Nval200-K25-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset creditcard --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-creditcard-Ntrain500-Nval200-K25-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset vehicle --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-vehicle-Ntrain500-Nval200-K25-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset click --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-click-Ntrain500-Nval200-K25-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset wind --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-wind-Ntrain500-Nval200-K25-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset pol --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-pol-Ntrain500-Nval200-K25-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset 2dplanes --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-2dplanes-Ntrain500-Nval200-K50-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset cpu --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-cpu-Ntrain500-Nval200-K50-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset phoneme --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-phoneme-Ntrain500-Nval200-K50-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset fraud --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-fraud-Ntrain500-Nval200-K50-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset creditcard --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-creditcard-Ntrain500-Nval200-K50-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset vehicle --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-vehicle-Ntrain500-Nval200-K50-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset click --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-click-Ntrain500-Nval200-K50-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset wind --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-wind-Ntrain500-Nval200-K50-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset pol --value_type KNN-SV-RJ --n_data 500 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-pol-Ntrain500-Nval200-K50-Kernel-plain-dist-l2.txt


python applications_knn.py --task mislabel_detect --dataset 2dplanes --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-2dplanes-Ntrain1000-Nval200-K25-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset cpu --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-cpu-Ntrain1000-Nval200-K25-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset phoneme --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-phoneme-Ntrain1000-Nval200-K25-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset fraud --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-fraud-Ntrain1000-Nval200-K25-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset creditcard --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-creditcard-Ntrain1000-Nval200-K25-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset vehicle --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-vehicle-Ntrain1000-Nval200-K25-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset click --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-click-Ntrain1000-Nval200-K25-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset wind --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-wind-Ntrain1000-Nval200-K25-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset pol --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-pol-Ntrain1000-Nval200-K25-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset 2dplanes --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-2dplanes-Ntrain1000-Nval200-K50-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset cpu --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-cpu-Ntrain1000-Nval200-K50-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset phoneme --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-phoneme-Ntrain1000-Nval200-K50-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset fraud --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-fraud-Ntrain1000-Nval200-K50-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset creditcard --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-creditcard-Ntrain1000-Nval200-K50-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset vehicle --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-vehicle-Ntrain1000-Nval200-K50-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset click --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-click-Ntrain1000-Nval200-K50-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset wind --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-wind-Ntrain1000-Nval200-K50-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset pol --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric cosine --normalize >> wtnn_result/KNNSV-Mislabel-pol-Ntrain1000-Nval200-K50-Kernel-plain-dist-cosine-norm.txt
python applications_knn.py --task mislabel_detect --dataset 2dplanes --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-2dplanes-Ntrain1000-Nval200-K25-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset cpu --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-cpu-Ntrain1000-Nval200-K25-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset phoneme --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-phoneme-Ntrain1000-Nval200-K25-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset fraud --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-fraud-Ntrain1000-Nval200-K25-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset creditcard --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-creditcard-Ntrain1000-Nval200-K25-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset vehicle --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-vehicle-Ntrain1000-Nval200-K25-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset click --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-click-Ntrain1000-Nval200-K25-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset wind --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-wind-Ntrain1000-Nval200-K25-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset pol --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-pol-Ntrain1000-Nval200-K25-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset 2dplanes --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-2dplanes-Ntrain1000-Nval200-K50-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset cpu --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-cpu-Ntrain1000-Nval200-K50-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset phoneme --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-phoneme-Ntrain1000-Nval200-K50-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset fraud --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-fraud-Ntrain1000-Nval200-K50-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset creditcard --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-creditcard-Ntrain1000-Nval200-K50-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset vehicle --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-vehicle-Ntrain1000-Nval200-K50-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset click --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-click-Ntrain1000-Nval200-K50-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset wind --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-wind-Ntrain1000-Nval200-K50-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset pol --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 --normalize >> wtnn_result/KNNSV-Mislabel-pol-Ntrain1000-Nval200-K50-Kernel-plain-dist-l2-norm.txt
python applications_knn.py --task mislabel_detect --dataset 2dplanes --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-2dplanes-Ntrain1000-Nval200-K25-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset cpu --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-cpu-Ntrain1000-Nval200-K25-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset phoneme --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-phoneme-Ntrain1000-Nval200-K25-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset fraud --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-fraud-Ntrain1000-Nval200-K25-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset creditcard --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-creditcard-Ntrain1000-Nval200-K25-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset vehicle --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-vehicle-Ntrain1000-Nval200-K25-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset click --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-click-Ntrain1000-Nval200-K25-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset wind --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-wind-Ntrain1000-Nval200-K25-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset pol --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 25 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-pol-Ntrain1000-Nval200-K25-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset 2dplanes --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-2dplanes-Ntrain1000-Nval200-K50-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset cpu --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-cpu-Ntrain1000-Nval200-K50-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset phoneme --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-phoneme-Ntrain1000-Nval200-K50-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset fraud --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-fraud-Ntrain1000-Nval200-K50-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset creditcard --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-creditcard-Ntrain1000-Nval200-K50-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset vehicle --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-vehicle-Ntrain1000-Nval200-K50-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset click --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-click-Ntrain1000-Nval200-K50-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset wind --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-wind-Ntrain1000-Nval200-K50-Kernel-plain-dist-l2.txt
python applications_knn.py --task mislabel_detect --dataset pol --value_type KNN-SV-RJ --n_data 1000 --n_val 200 --flip_ratio 0.1 --K 50 --n_repeat 1 --dis_metric l2 >> wtnn_result/KNNSV-Mislabel-pol-Ntrain1000-Nval200-K50-Kernel-plain-dist-l2.txt


